name: easy_timezone
description: A very easy to use timezone package to Dart and Flutter.
version: 1.0.2
repository: https://github.com/gzlock/dart_easy_timezone

environment:
  sdk: '>=2.19.6 <4.0.0'
dependencies:
  http: ^1.2.1
